name: Build Android APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install gcc libgl1-mesa-dev xorg-dev
        go install fyne.io/fyne/v2/cmd/fyne@latest

    - name: Build APK
      run: |
        $(go env GOPATH)/bin/fyne package -os android -appID com.ocean.checker -icon Icon.png

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Hot-Ocean-APK
        path: "*.apk"
